### ISSUE TITLE
请问如何编译安卓适用的alist？

### ISSUE THREAD

**Issue by ToSeeAll** [X-yael/AlistforMagisk#1]
rt，请问老哥是如何编译的？我通过电脑编译的用不了，手机上用LinuxDeploy里的ubuntu编译不成功

**Comment by hnshandy** [comment]
> 看到博客了

博客似乎不能访问了，我也要求教，愿意付费，看到麻烦回复。

**Comment by X-yael** [comment]
刚弄好了 联系可以用飞机xyj249

**Comment by X-yael** [comment]
> > 看到博客了
> 
> 博客好像不能访问了，我也要求教，愿意付费，看到麻痹回复。

好了 需要联系的话telegram@xyj249

**Comment by hnshandy** [comment]
> 

不好意思 我没有tg，也没有vpn
原来这个要root？那我用不上了。
