### ISSUE TITLE
请更新 Alist版本，现有的3.3.0版本阿里云盘无法挂载了。

### ISSUE THREAD

**Issue by StormGens** [X-yael/AlistforMagisk#3]
请更新 Alist版本，现有的3.3.0版本阿里云盘无法挂载了。

ReadMe里面的博客地址无法访问。

感谢！

**Comment by X-yael** [comment]
好了

**Comment by X-yael** [comment]
> 

3.11.0

**Comment by X-yael** [comment]
> 请更新 Alist版本，现有的3.3.0版本阿里云盘无法挂载了。
> 
> ReadMe里面的博客地址无法访问。
> 
> 感谢！

3.11.0

**Comment by X-yael** [comment]
已更
